apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-python-deployment
  namespace: default
  labels:
    app: eks-sample-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-python-app
  template:
    metadata:
      labels:
        app: eks-sample-python-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: linux
        image: 741506559500.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux