apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: 741506559500.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
        
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80